### ISSUE TITLE
switch to typesript

### ISSUE THREAD

**Issue by JumpyLionnn** [retro-mmo-com/vod-player#24]
development on this project will be much easier with typescript

**Comment by evannorton** [comment]
Typescript support would be great, but I definitely don't wanna move away from GH Pages. We can maybe make this work without moving away from GH Pages by using its newly added support for GH Actions deployment.  I would prefer that the build process be using TSC to compile multiple files -> using ESBuild to bundle to a singular file. If someone wants to do a PR for this, they would probably need to enable GH pages on their forked repo to test.

"GitHub Actions" instead of "Deploy from a branch"
![image](https://user-images.githubusercontent.com/35230033/184422460-c0a909c4-ee7c-4952-89db-75cd462eed0e.png)
